### ISSUE TITLE
Program crash after opening a WPA file

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#13]
- Start program
- open an existing WPA file
- click "Animation Settings"
Program crash

**Comment by JoostZ** [comment]
The old saved files didn't store sthe stroke timing. When going in the animation setting the validation rules (that were added some timeago)tried to use the stroke timing which lead to a null-pointer exception.

Added in the load functionality a check if the stroke timing is available and if not, it is added.
