### ISSUE TITLE
new default values for static parameters and segment definitions

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#17]
See below figures

![new_default](https://cloud.githubusercontent.com/assets/5354652/22403704/dfd5869e-e61f-11e6-8cf1-cd4fdc01ad2e.png)
![new_static](https://cloud.githubusercontent.com/assets/5354652/22403703/dfd581bc-e61f-11e6-913b-92804a7d0976.png)

**Comment by JoostZ** [comment]
Updated defauls, except fot the handheight since we only initate a single segment
