### ISSUE TITLE
plot the position of the handle during the rowing cycle

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#19]
- use an alternate colour
- redraw after restarting animation

**Comment by JoostZ** [comment]
Note that we can do something similar as we do with the proflre: We use the animation to run once through the hole cycle. We can then retrieve the handpositiononce ad store it!

**Comment by Tomhz** [comment]
There is no need to store it. I would like to see it plotted in the animation after running once through the whole cycle.

**Comment by Tomhz** [comment]
Maybe I am too late, but I would like the option to show and clear this track by choice in the animation. If you think I am, I will create a new enhancement issue for this.

**Comment by JoostZ** [comment]
I was considering to have a checkbox at the bottom of the window that would sow/not show the position.

I am running in problems with implementing the show. It is really slow so I am not yet sure what to do ☹️. So it is not too late to do something about showing the track. Do you think a checkbox would be a good idea?

**Comment by Tomhz** [comment]
Yes a checkbox is good. Showing the track is not always needed and may even distract. 
I can imagine that the default should be "no track" and that after enableing this you only need to track one whole stroke. That might be the solution for the slow tracking?

**Comment by JoostZ** [comment]
I am already generating the track only once. However, if a parameter is changed or, what I am encountering now, the window is resized then I need to re-generate the track. And that is slow. Apparently when I resize the window I get multiple events telling it is resized (probably multiple small steps of the total resize) and every time the track is re-generated.

**Comment by Tomhz** [comment]
Maybe you should leave this issue for a while. #63 somewhat is a poor-man alternative for this issue and will be much easier to build

**Comment by Tomhz** [comment]
It does work. But resizing the window to full screen takes 8-12sec, with or without the "show track" box checked.

**Comment by JoostZ** [comment]
I will take a closer look at the slowness. I do understand why it is also slow if the track is disabled. It is because I calculate the track then also. Yhe checkbox just hides it.

**Comment by JoostZ** [comment]
Found the issue and solved it

**Comment by Tomhz** [comment]
It is solved indeed. With the "show track" option. I don't need the horizontal lines anymore. I will update that issue.

**Comment by Tomhz** [comment]
I like this enhancement more than I had expected. I helps a lot.
