### ISSUE TITLE
Add a grid in the animation

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#21]
I think a 4-5cm grid would be best suitable

**Comment by Tomhz** [comment]
This is only possible when the software is more aware of position and distance

**Comment by JoostZ** [comment]
The software *is* aware of position and distance. But for this issue I am not sure if this is needed. I have started implementing this and I now have 3 horizontal lines.

It is not clear from your description if you want 4-5 cm of the world coordinates, i.e., regarding the position of, e.g., the seat, or of graph coordinates, i.e., the distance between the lines *on the screen* would be 4-5 cm.

the world coordinates in the graph are currently between XMin = -50 and XMax = +130.  So if you want the grid in world coordinates there would be 36 vertical lines (180/5).

**Comment by Tomhz** [comment]
I meant world coordinates.  
Vertical lines are much more useful than horizontal lines Horizontal lines are only useful for vertical movements around catch and tap out (inpik and uitpik). I even wonder if horizontal lines would make the screen too crowded.

**Comment by Tomhz** [comment]
I see three horizontal lines now in 1.0.6527
However, vertical lines 5cm apart are more useful.

**Comment by JoostZ** [comment]
Yes I am aware of that now. It was not clear originally in this issue.

Do you want any horizontal lines or should I leave them out?

B.t.w., I think it might be useful to have some extra lines, such as, e.g., the position of the slider. But I think that should be a separate enhancement. Can you think  about such an enhancement?

**Comment by Tomhz** [comment]
I don't need the horizontal lines, only vertical. 
There is one horizontal line i would like: a bit lower than the lowest point of the handle during the stroke, This will show more accurately  the small vertical movements of the handle. 
But i think this is not about a grid, but a separate enhancement. What do you think?

**Comment by JoostZ** [comment]
Yes I agree about a new enhancement for the horizontal line. I will use this issue (#21) to remove the horizontal lines.

**Comment by Tomhz** [comment]
About the vertical lines: I think I might not need this when issue #24 is realised. So I think we should pause this enhancement. Removing the horizontal lines is still welcome.

**Comment by JoostZ** [comment]
If you agree, you can open a separate issue to remove the horizontal lines. There is very little work in this so I would take it in quickly (put it high in the ToDo list). Then we can pause the current issue. Maybe you can move it out of the project and maybe create a new label 'On Hold' so that we can keep track of it.

**Comment by Tomhz** [comment]
The current version, including data overlay shows sufficient information. The grid is no longer needed
