### ISSUE TITLE
show the actual numerical position of handle in animation

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#24]
in the same way as the time is shown. 
Zero point is :  closest to the body.

**Comment by JoostZ** [comment]
Add a readonly field in first tab next to HPos. Can be based on handpos.X in rower,cs

**Comment by JoostZ** [comment]
@Tomhz : I am not sure what you want here. You mention that the zero point is closest to body. That is how it is done with the HPos parameter, but it is a relative value (0-1). Do you want this converted to an absolute value (incorporating the arm length) or the position in the coordinate system where 0 is the heel and you include the position of the seat etc.

**Comment by Tomhz** [comment]
My request is about world coördinates of the handle, with the zero point closest to the body. In that way, the point furthest from the body will be equal to the drive length.

**Comment by JoostZ** [comment]
I still don't get it. The zero point would change during the stroke. At the catch the body is more forward than at the release, both because of the slider and the back angle. So if I give the handle position regarding that point it will in fact be the length of the arms. So if you make an animation where the arm remains stretched (you only move the seat and the back angle) then the handle position would remain constant and it would not be the drive length.

What am I missing?

**Comment by Tomhz** [comment]
It is about the position of the handle in world coordinates. Just as you calculate and show the total stroke length in the Animation Settings Tab. The Stroke length is the distance between the handle position at the catch and the release. My request is about showing the distance between the current handle position and the release in the Animation window. 
With this enhancement realised, I even wonder if I still want the vertical grid lines from #21. Therefore I will lower the priority of #21 in the project

**Comment by Tomhz** [comment]
It works great. Nice feature, I think I would prefer to see this position value in the Right animation screen, next to the T Value. 
But i see there is not enough space on that line when in the left part the "Animation Setting" Tab is selected. 
I think I should create a new enhancement-issue for that and close this issue. Do you agree?

**Comment by JoostZ** [comment]
Agree.

**Comment by JoostZ** [comment]
Funny, I didn't like to put the position in the first tab but I thought you had requested it. Now I see that I made the suggestion :smile:.
