### ISSUE TITLE
When changing Tempo the segments become invalid

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#26]
Changing the Tempo or Drive Time will change the end values of the segments (they are between 0 and drive/recover time. However, the segment definition is not updated. That means that the segment definitions become invalid.

Should we do something about this, e.g., try to update the segment definition?

**Comment by Tomhz** [comment]
That seems a good idea. 

- Changing the tempo just changes the recovery time. Only the definitions of the recovery segments should be changed, i think in proportion with the ratio of the change in recovery time. 
- When changing the drive time  only the definitions of the stroke segments should be changed, i think in proportion with the ratio of the change in drive time.

**Comment by Tomhz** [comment]
Oops, I did not want to close this issue.

**Comment by JoostZ** [comment]
Implemented rescaling.

**Comment by Tomhz** [comment]
Works nice
