### ISSUE TITLE
Length of total stroke seems always 1.4m in the profile graph

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#27]
[very short stroke.zip](https://github.com/JoostZ/ShowRow/files/1451783/very.short.stroke.zip)

I have added an rwa file with an estimated stroke length of 30cm, buth the profile length is 1.4m

**Comment by JoostZ** [comment]
The horizontal axis in the profile screen is time. At the top is the Drive time, at the bottom the recover time.

**Comment by JoostZ** [comment]
Now added labels on the top and bottom of the graph to make this clear. See #28

**Comment by Tomhz** [comment]
Agree
