### ISSUE TITLE
Add titles for the axis in the profile graph

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#28]
I think they are: 

distance (m) for the bottom horizontal
time (s) for the top horizontal
(handle) speed (m/s) for the vertical

**Comment by Tomhz** [comment]
I understand I assumed wrong. Horizontal are time values. 
But what is the vertical value?

**Comment by JoostZ** [comment]
Implemented. Will be in next development build to be verified.

**Comment by Tomhz** [comment]
Ok, done
