### ISSUE TITLE
show total stroke length numerically in animation setting 

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#29]
As a non-editable derived value in the "Limits" box.

**Comment by Tomhz** [comment]
See my comment in issue 30

**Comment by Tomhz** [comment]
I am thinking: in the profile graph you are showing handle speed (in the black line) versus time. Integrating this you get a distance.  Apperently, the software has some awareness of handle position. 

Doing a course integration myself I get reasonable total stroke length of 120cm, close to 120-140cm stroke lengths i see on the ergometer.

**Comment by JoostZ** [comment]
I do have the position of all points of the rower. So I can indeed generate the stroke lengths. In fact, to get the velocity in the profile graph I do a numerical differentiation.

**Comment by Tomhz** [comment]
This would be nice. 
I have an ergometer app that connects to the PM3 and it shows Drive Speed and Stroke Length for each stroke. So showing these values in ShowRow helps me to decide if Static parameters and Segment Limits are OK.

**Comment by JoostZ** [comment]
Implemented. Needs to be reviewed in next development build.

**Comment by Tomhz** [comment]
This is useful. I will add an enhancement request later to add the units (cm and cm/sec) and to use the terms Drive and Stroke consistently in the Animation Settings screen.
