### ISSUE TITLE
show average stroke speed numerically in animation setting 

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#30]
As a non-editable derived value (stroke length divided by drive time) in the "stroke timing" box.

**Comment by Tomhz** [comment]
This requires the calculation of stroke length, being the distance between the posotion of the handle at start and finish of the stroke. This is a useful metric for me. 
But i understand it is hard to calculate, because you just "show" the limbs, not calculate their start- and endpoints? 
Maybe you could try this, knowing the length and angles of the limbs?

**Comment by Tomhz** [comment]
I think this could easily combined with #29

**Comment by JoostZ** [comment]
I am assuming you mean the length of the drive, right? For me the Stroke is the whole of the movement (from Catch to Catch) and the Drive is from Catch to Release.

I have no problem in calling it Stroke Length in the UI. Just want to be sure.

**Comment by JoostZ** [comment]
Implemented. Needs to be reviewed in next development build.

**Comment by Tomhz** [comment]
This is useful. I will add an enhancement request later to add the units (cm and cm/sec) and to use the terms Drive and Stroke consistently in the Animation Settings screen.
