### ISSUE TITLE
After loading an RWA file the segment definitions don't change but animation looks good.

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#33]
After loading an RWA file, the "From" and "To" parameters of the segment definition are equal to the default value. They are shown correctly in the "Limits" box, though. The animation looks good and reflects the values in the "Limit" box. 

Try this with the RWA in the included ZIP-file 
[very short stroke.zip](https://github.com/JoostZ/ShowRow/files/1451949/very.short.stroke.zip)

**Comment by JoostZ** [comment]
Was missing a notification. Is solved now

**Comment by Tomhz** [comment]
Solved. Nice.
