### ISSUE TITLE
Change default values of stroke timing

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#35]
Default for Drive time is now 1.07. Change that to 0.9.  This reflects more a realistic drive time. 

Unfortunately this messes up the default Stroke segment timing. So we could definitely use the enhancement from issue #26

**Comment by JoostZ** [comment]
Done. I also changed the segment values to match this new value using the fix of #26 . However, the segment values are hard coded so it should be reviewed if these values are correct. If not, they can be changed.

**Comment by Tomhz** [comment]
Segment timing looks good. I will close this issue
