### ISSUE TITLE
In segment editor, change the accuracy of the values of acceleration, decelaration and speed to 4 digits

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#36]
To prevent overflow and to match better the actual accuracy.

**Comment by Tomhz** [comment]
But I like that these values are show!

**Comment by JoostZ** [comment]
It is currently limited to 4 decimal places. Do you mean to limit to 4 digits in total so 11.1234 would be shown as 11.123?

**Comment by Tomhz** [comment]
Yes. To prevent overflow in the box.

**Comment by JoostZ** [comment]
Implemented. Waiting for testing in next development build.

**Comment by Tomhz** [comment]
When the constant velocity gets below 1, it shows 5 instead of 4 decimals. This requires 6 digits, but this fits in the box, so we could call this fixed
When the acceleration or deceleration get below 1 (this is pretty rare),  it shows 5 instead of 4 decimals. This requires 6 digits and that does **not** fit in the box. 

I suggest that we call this fixed and make a new issue to increase the boxes for acceleration and  deceleration to the same size as the box for velocity. OK?
