### ISSUE TITLE
In segment editor add units (m/sec and m/sec2) to speed and accelaration values

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#37]

**Comment by JoostZ** [comment]
This is not always possible. For the seat and HandPosition the parameter is dimensionless. So there is no m/sec. For the Seat it would be possible to calculate the distance of the seat to the foot board but for the hand position such a  calculation depends on the value of other parameters so I don't think it could be done.

For the back it would be degrees/second.

**Comment by Tomhz** [comment]
You are right.
