### ISSUE TITLE
Add the possibility to choose the "split point" when splitting a segment

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#42]
It is now splitted at a standard point about halfway From and To of the original segment

**Comment by Tomhz** [comment]
I think this is allready possible, by using the sliders in the segment editor. I misinterpreted these sliders when using the segment editor. 

Do you agree? I will close this issue if you do.

However: I think i found one ore more bugs in these sliders after a segment split. I will create new issues for that

**Comment by JoostZ** [comment]
OK, it was not clear to me what exactly you meant. I thought that you wanted to be able to specify the split point _before_ the split, which would be tricky, not from an implementation point of view but how to do this in the UI.. But indeed, you can change the split point after the split so if this is OK with you then you can close the issue.
