### ISSUE TITLE
When splitting a segment the From-field of the first segment becomes editable

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#43]
The yellow colour changes to white and you can change it value. This should not be, as it is dictated by the parameters in the Limits box.

The To-field of the second segment stays Yellow. This is correct
The To-field of the first segment and the From-Field of the second become white and editable. This is correct

**Comment by JoostZ** [comment]
Implemented. Ready to be reviewed in the next development build.

**Comment by Tomhz** [comment]
Yes, now it is OK. Even when splitting in three: the From field of the first and the To field of the last are dictated by the Limit parameter of the corresponding segment. The are yellow and read-only as they should be. The others are white and editabled and the values of neighbouring fields are mutually coupled
