### ISSUE TITLE
Add the possibility to change the "split point" of a splitted segment

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#44]
The To-Field of the first segment should always stay equal to the From-field of the second segment. 
I would like to have a slider to change it. 

An alternative is to make the From-field of the second segment Yellow and non-editable and keep it equal to the white and editable To-Field of the first segment.

**Comment by JoostZ** [comment]
The plan was that when you edit either the To of the first or the From of the second segment then the other one would also change. This is clearly not happening and so this is a bug.

When I would fix this it would basically be your alternative solution.

**Comment by Tomhz** [comment]
I would like to have this fix, even as it moves aways from other plans to stop editting segment parameters manually. Changing the split point afterwards is a very usefull feature.
So this changes this enhancement to a bug. 
We might add an enhancement later to add a slider to do this.

**Comment by JoostZ** [comment]
I created bug #49 and close this issue now.
