### ISSUE TITLE
When splitting a segment the split point shows too many decimals. 3 is ok

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#45]

**Comment by JoostZ** [comment]
Which data is showing more then 3 digits? And in which view: Editor or Segment List?

**Comment by Tomhz** [comment]
This is about the values in the To and From field in the segment list, after a split.  They show 16 decimal places. When editing the segment, thes values are rounded to 3 decimals and this is OK. After changing and saving in the Segment editor, they again have 16 decimals in the segment list.

**Comment by JoostZ** [comment]
Implemented. Needs to be reviewed for the formatting in the next development build.

**Comment by Tomhz** [comment]
Good
