### ISSUE TITLE
Do we need changes in the trapezium model?

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#47]
The trapezium model for the segments was basically dictated by the animation framework I use, which is a built-in framework. Fortunately this approach works pretty well but there are some limitations. For instance it is not possible for a parameter to accelerate to a constant velocity, keep moving at that velocity and the accelerate to a new constant velocity. In the current approach you have to end the first segment by decelerating to 0 and then accelerate from 0 to the new velocity.

I have now changed the animation method. In fact I can now animate a control parameter with basically any function of time. So it would be possible to modify the trapezium method. The problem I see is the modelling and the how to put something like that in the UI.

Have you run into problems with the current approach and what are your thoughts on this?

**Comment by Tomhz** [comment]
I remember vaguely I once needed something that could not be modeled by a trapezium, but i don't know the details anymore. 
So I think your new animation method is useful but i do not have an application yet

**Comment by JoostZ** [comment]
OK, I close this issue for now and we keep it in mind if there is an application. We should have a better idea then how to model it.
