### ISSUE TITLE
Should we change the use of limits?

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#48]
Currently the position of the control parameters at the catch and release are at the same time the limits of the From and To. This means, e.g., that the seat cannot move forward at the catch. I think it is not possible to model 'door je bankje trappen', where at the catch the trunk would move forward while the seat moves backward, keeping the hand at the same position.

We could remove the From (and To) limit and use the limit settings only to determine the position of the rower at catch and release. It would of course require the modeler (you :smile:) to be sensible in what From and To values are specified.

What do you thin? Is this worthwhile exploring?

**Comment by Tomhz** [comment]
I think i can model "door je bankje trappen" with the current setup. I would split the trunc movement of the  stroke segment and start the stroke with a negative movement of the trunc. With the current bugs in the segment editor in combination with splits i might need to edit the T0-T3 parameter manually.
I will try it and add the RWA file in a comment. 

At the moment I don't think we should remove the From and To limit. I suggest we will discuss this in december

**Comment by Tomhz** [comment]
Here is an RWA file that shows "door het bankje trappen". "Bum shoving" in english. 
After splitting the Trunc segment I had to change the To field of the first and the From field of the second. The segment Editor cannot do that. So that is another kind of Split variation that might be needed: not only the time of the split but also the position of the segment at the split.   

[door bankje trappen.zip](https://github.com/JoostZ/ShowRow/files/1468734/door.bankje.trappen.zip)

**Comment by JoostZ** [comment]
Right, that you can do it in the segmentlist is in fact a bug. The limits section was intended to give the limits of the control parameter. The segment editor implements it ass intended., 

Now you understand why I asked this question. And the answer is that indeed we should make a difference between edgevalues (the values at the moment of the catch and release) and the limits of the parameters. We specifically need the limits in the Segment Editor since we use a slider, which has a minimum and a maximum value.

I will create an enhancement issue to request the implementation.

**Comment by JoostZ** [comment]
Created #50
