### ISSUE TITLE
In segment Editor improve the distinction between read-only and changeable  Limits sliders

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#53]
When changing the limits of a sub-segment (maybe we should start using this term) one of the Limits sliders is read-only and the other is changeable. When the segment is split in 3 subsegments the middle subsegment has both changeable sliders.
It took me a while to notice when a slider is changeable. The read-only one is greyed out somewhat. 
Maybe you can add a yellow colour for read-only sliders? 
Or maybe there shouldn't be a slider at all for a fixed value?

**Comment by JoostZ** [comment]
I pick this up since it is a simple change and I am working on these sliders anyway (for #64 ). I will make the unchangeable sliders invisible.

**Comment by Tomhz** [comment]
Good. This improves the natural user interaction.
