### ISSUE TITLE
In segment editor the T3 of the 2nd subsegment can be pushed out of the screen and T3 value will go over its limit

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#54]
This is in version 1.0.6527.
I need to find out in what circumstances this can happen. I will try to find a "recipe" to do it.

**Comment by JoostZ** [comment]
I think this is related to #55. There is something wrong with splitting and the setting of the limits.

**Comment by Tomhz** [comment]
You need to be aware that i found this bug by doing some random changing of the splitted segment. I don't know if I will run into this bug in realistic situations. I fact up to now I only tested changing splitted segments without the purpose to create realistic rower movements. I will do that soon

**Comment by JoostZ** [comment]
I cannot reproduce this. Can you try to find a situation where it occurs and describe the scenario?

**Comment by Tomhz** [comment]
I can reproduce it either with the current 6534 release, but i didn't try hard enough. I will try some more.

**Comment by Tomhz** [comment]
OK, I think this is solved indeed in this or a previous release after 6527. I am OK to close it. OK with you?

**Comment by JoostZ** [comment]
Yes, I agree, lets close it.
