### ISSUE TITLE
Remove the spurious "Analysis" Tab?

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#62]

**Comment by JoostZ** [comment]
I wondered when you would notice :smile:.

When you brought up the new project biorow, you remember, the one where we would physically measure the position of the handle, I decided to do some experimenting with software part, using RowAnimation to get data. This was on a separate branch but through some mistakes I made it all got on the develop branch. It doesn't show anywhere, except for the extra tab.

I will remove it.

**Comment by Tomhz** [comment]
This issue did not get the Review Label although you did movve it to the In Review column in the project.

The issue can be closed.
