### ISSUE TITLE
In some segments, after a split both Limits Sliders are read-only. In fact, one of them should be changeable

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#64]
I will find out which segments.

**Comment by Tomhz** [comment]
The bug is in thse segments

- Stroke/drive  Backangle
- Stroke/drive handposition
- Recover handheight
- Recover Seat

The other segments are OK (one changeable Limit Slider)

**Comment by Tomhz** [comment]
This makes the split-segment functionality unusable for these segments, so therefore i have put it on top of the list

**Comment by JoostZ** [comment]
I have a strong feeling it has to do with the facts that in these segments the To < From.

**Comment by JoostZ** [comment]
Note that in the latest build the change of From or To is not shown in the graph. This is on all segments. I broke the code ☹️. I will fix it with this issue.

**Comment by Tomhz** [comment]
Nice! It works OK now
