### ISSUE TITLE
Allow to save a snapshot of the animation window as an image.

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#65]
This is a pre-cursor for #60. One of the tasks for that issue is to extract the rower from the display. Allowing to save it to disk is a good way to test. We can decide later if we want to keep the save functionality.

**Comment by JoostZ** [comment]
First result: I have a PNG.
![rowimage](https://user-images.githubusercontent.com/4018815/32980395-23af0c46-cc66-11e7-8f7e-10598f232f0b.png)

**Comment by JoostZ** [comment]
When saving the image the program takes exactly the size and shape of the window. It also only shows the hand position if the checkbox is selected. It is like a screenshot.

**Comment by Tomhz** [comment]
Looks good. Indeed, i can choose between with or without Handle track. The PNG is nice small: 10KB
