### ISSUE TITLE
Create a data overlay in the Rower display

### ISSUE THREAD

**Issue by JoostZ** [JoostZ/ShowRow#71]
To help answer the question #61 I would like to create a data overly that will show the coordinates of the different points of the rower in the display. It is probably going to be a temporary display that we will remove later but, who knows, it might be an interesting feature.

**Comment by JoostZ** [comment]
I have created build 6542.21141 that has a data overlay. it is really slow in animation but it does show the important data that is calculated.

It has the (world) coordinates of the important points and the actual length associated with the parameters handPosition and Seat.

Note: This build does not contain the changes in the Segment Editor. It is on a separate branch so it can easily be removed again.

@Tomhz can you take a look at the numbers and see if you can understand the difference as reported in #61?

**Comment by Tomhz** [comment]
This Data Overlay helps.
I think the Rowanimation calculations are OK. I need to change the Static and Limit parameters to  get  the Stroke length to >130.
Here are my own measurements:
![rowanimation_19](https://user-images.githubusercontent.com/5354652/33398477-61cd3d9e-d54f-11e7-9449-878e96e94f6b.png)

I will play around with the parameters and might ask for a change of the defaults.  On the other hand, the current 110-115 stroke length of the default is appropriate for women.

**Comment by Tomhz** [comment]
Should we close this issue with the Data Overlay? I think I will need this Data Overlay function incidentally for further measurements.  I can use 6542 for that ofcourse, but maybe you can add this using a checkbox?

**Comment by JoostZ** [comment]
I will implement a checkbox and then put it in the main stream. I assume you also want to have the possibility to show the overlay in saved PNG and/or GIF?

**Comment by Tomhz** [comment]
Yes. 
There is no added value in showing this in the animated GIF but as long as I can uncheck it when writing PNG/GIF it is fine.

**Comment by JoostZ** [comment]
Ready for testing. Added a checkbox to control the display of the overlay. I also added check boxes for the Handle trace and Data Overlay in the Save Image box.

**Comment by Tomhz** [comment]
Nice.  I like this Data overlay check box. The Data Overlay in the animated GIF might be useful too
