### ISSUE TITLE
This is a nice tool for Animated Gifs

### ISSUE THREAD

**Issue by Tomhz** [JoostZ/ShowRow#72]
[https://ezgif.com/gif-to-mp4](https://ezgif.com/gif-to-mp4)

It can play animated Gifs much smoother than the default app in Windows
And it can do the conversion to MP4 with >5x size reduction
and much more

**Comment by JoostZ** [comment]
The formatting of the link was not correct. The part between [] is the text shown in the isuue and the part in () is the actual URL. I added the link so now you can click on it.

**Comment by JoostZ** [comment]
It looks indeed nice! I haven't found a way to auto-repat the MP4. Do you know if it is even possible?

**Comment by Tomhz** [comment]
The standard Windows 10 "Films and TV"  has the option to repeat the MP4 when playing. 
The popular MP4 player VLC has the same option
