### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by baszalmstra** [JoostZ/ShowRow#79]
A license seems to be missing.

**Comment by JoostZ** [comment]
Good point! this brings up, of course, what the license should be. I personally would go for an open source license but I think Tom may have a different view on this.

@Tomhz  what do you think?

**Comment by Tomhz** [comment]
Joost, 
Ik kan even niet github gebruiken vanwege WiFi problemen. 
Ik zal de issue later aanvullen. 
Ik sprak gisteren mijn neef Jaap die roeicoach is/was in Delft. Bas was er ook. Jaap dacht dat zijn vereniging wel in Rowanimation geïnteresseerd zou zijn. Coaching gaat daar bijna professioneel en er is geld beschikbaar voor alles wat instructie en coaching kan verbeteren.
Maar hij zei ook dat ze niet zo snel in zee zullen gaan met een persoon. Om licenties te kunnen verkopen zou een bedrijf nodig zijn met enige zekerheid over continuïteit en ondersteuning. Dat is niet iets dat ik ambieer. Nu niet in ieder geval. 
Ik zei tegen Bas dat we in github werken en hij vroeg jouw github naam  . Toen hij inlogde met zijn account en de code bekeek en de issue over de licentie aanmaakte realiseerde ik me pas goed dat iemand (bv iemand van de roeivereniging van Jaap) met ons idee en product aan de haal kan gaan en zelfstandig verder kan ontwikkelen. Natuurlijk kan het ook positief uitpakken en krijg je met zo iemand versterking bij ontwerp, bouw en testen. 
Dus ik wil graag nog een keer de discussie voeren over wel/niet publiekelijke beschikbaarheid van de code, de mogelijkheden van een private repository, en mogelijkheden voor licentie teksten in github om de mogelijkheid te verkleinen dat iemand met ons product aan de haal gaat zonder ons daarin te kennen.

Dat kan het beste als je bij ons bent. 
Kom je donderdag? Weet je al hoe laat? Ik haal je dan van station Nunspeet.

Tom

**Comment by Tomhz** [comment]
See your mail

**Comment by Tomhz** [comment]
We are moving the project to a private VSTS. There we will do the discussion about licensing
